# Generated by Django 3.1.4 on 2021-01-08 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='entradamodel',
            name='image_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entradamodel',
            name='pub_date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='SingleEntradaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.entradamodel')),
            ],
        ),
        migrations.AlterField(
            model_name='entradamodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.autormodel'),
        ),
    ]
