# Generated by Django 3.1.4 on 2021-01-08 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210107_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entradamodel',
            old_name='author',
            new_name='author_id',
        ),
    ]
